### ISSUE TITLE
Looks like API changed

### ISSUE THREAD

**Issue by arsaboo** [Liupold/fmdpy#23]
Getting this error:
```bash
Traceback (most recent call last):
  File "/home/arsaboo/.local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arsaboo/.local/bin/fmdpy", line 8, in <module>
    sys.exit(fmdpy())
  File "/home/arsaboo/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/fmdpy/__main__.py", line 112, in fmdpy
    song_list = find_songs(search, count)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/fmdpy/prompt.py", line 22, in find_songs
    song_list = query(search_str, count)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/fmdpy/api.py", line 94, in query
    return query_songs_search(query_string, max_results)
  File "/home/arsaboo/.local/lib/python3.10/site-packages/fmdpy/api.py", line 58, in query_songs_search
    return parse_query(req.json())
  File "/home/arsaboo/.local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Liupold** [comment]
Sorry for the late reply. Can you try again ? Also try out the git version. It's working fine for me.

**Comment by arsaboo** [comment]
It is working...looks like it was a temporary outage.
